
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =            1743
     no. of nonzeroes in lower triangle of a =           96439
     no. of nonzeroes in the factor l        =          226291
     ratio of nonzeroes in factor (min/max)  =          0.6961
     number of super nodes                   =              46
     maximum order of a front matrix         =             204
     maximum size of a front matrix          =           20910
     maximum size of a front trapezoid       =           19701
     METIS reordering method used 
     no. of floating point ops for factor    =      2.6826D+07
     no. of floating point ops for solve     =      8.0992D+05
     ratio of flops for factor (min/max)     =          0.5479
     ratio of allocated memory (max/min)     =          1.2709
     number of positive pivots               =            1743
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000260
     time (cpu & wall) for ordering          =        0.000000        0.003187
     time (cpu & wall) for other matrix prep =        0.000000        0.002562
     time (cpu & wall) for value input       =        0.000000        0.000673
     time (cpu & wall) for matrix distrib.   =        0.062500        0.007833

     no input or output performed

  Solver Memory allocated on core    0       =        1.552 MB
  Solver Memory allocated on core    1       =        1.772 MB
  Solver Memory allocated on core    2       =        1.533 MB
  Solver Memory allocated on core    3       =        1.394 MB
  Total Solver Memory allocated by all cores =        6.252 MB

