
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =            1744
     no. of nonzeroes in lower triangle of a =           96532
     no. of nonzeroes in the factor l        =          226387
     ratio of nonzeroes in factor (min/max)  =          0.6806
     number of super nodes                   =              46
     maximum order of a front matrix         =             204
     maximum size of a front matrix          =           20910
     maximum size of a front trapezoid       =           19701
     METIS reordering method used 
     no. of floating point ops for factor    =      2.6835D+07
     no. of floating point ops for solve     =      8.1029D+05
     ratio of flops for factor (min/max)     =          0.5483
     ratio of allocated memory (max/min)     =          1.2649
     number of positive pivots               =            1744
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000241
     time (cpu & wall) for ordering          =        0.046875        0.003018
     time (cpu & wall) for other matrix prep =        0.000000        0.002645
     time (cpu & wall) for value input       =        0.000000        0.000669
     time (cpu & wall) for matrix distrib.   =        0.000000        0.007960
     time (cpu & wall) for numeric factor    =        0.093750        0.020495
     computational rate (gflops) for factor  =        0.286235        1.309295

     no input or output performed

  Solver Memory allocated on core    0       =        1.574 MB
  Solver Memory allocated on core    1       =        1.760 MB
  Solver Memory allocated on core    2       =        1.536 MB
  Solver Memory allocated on core    3       =        1.392 MB
  Total Solver Memory allocated by all cores =        6.262 MB

