
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =            1800
     no. of nonzeroes in lower triangle of a =           99846
     no. of nonzeroes in the factor l        =          229770
     ratio of nonzeroes in factor (min/max)  =          0.6270
     number of super nodes                   =              50
     maximum order of a front matrix         =             204
     maximum size of a front matrix          =           20910
     maximum size of a front trapezoid       =           19701
     METIS reordering method used 
     no. of floating point ops for factor    =      2.7054D+07
     no. of floating point ops for solve     =      8.2408D+05
     ratio of flops for factor (min/max)     =          0.5204
     ratio of allocated memory (max/min)     =          1.2690
     number of positive pivots               =            1800
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000267
     time (cpu & wall) for ordering          =        0.000000        0.002490
     time (cpu & wall) for other matrix prep =        0.000000        0.002344
     time (cpu & wall) for value input       =        0.000000        0.000819
     time (cpu & wall) for matrix distrib.   =        0.046875        0.006191
     time (cpu & wall) for numeric factor    =        0.031250        0.015817
     computational rate (gflops) for factor  =        0.865736        1.710431

     no input or output performed

  Solver Memory allocated on core    0       =        1.791 MB
  Solver Memory allocated on core    1       =        1.696 MB
  Solver Memory allocated on core    2       =        1.505 MB
  Solver Memory allocated on core    3       =        1.412 MB
  Total Solver Memory allocated by all cores =        6.404 MB

